apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: echo-server=git.home.williamlhunter.com/whunter/hashecho
    argocd-image-updater.argoproj.io/hashecho.update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: https://git.home.williamlhunter.com/whunter/hashecho
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
