on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go build -o app .
      - run: |
            curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-27.5.1.tgz | tar xz
            mv docker/docker /usr/local/bin/
            rm -rf docker
      - run: docker login --username whunter --password ${{ secrets.REGISTRY_TOKEN }} git.home.williamlhunter.com
      - run: |
          TAG=$(git rev-parse --short HEAD)
          docker build -t git.home.williamlhunter.com/whunter/hashecho:$TAG .
          docker tag git.home.williamlhunter.com/whunter/hashecho:$TAG git.home.williamlhunter.com/whunter/hashecho:latest
          docker push git.home.williamlhunter.com/whunter/hashecho:$TAG
          docker push git.home.williamlhunter.com/whunter/hashecho:latest
