on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go build -o app .
      - run: |
            curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-27.5.1.tgz | tar xz
            mv docker/docker /usr/local/bin/
            rm -rf docker
      - run: docker info
      - run: |
            mkdir -p /etc/docker
            echo '{"insecure-registries":["forgejo-http:3000"]}' > /etc/docker/daemon.json
            docker login --username whunter --password ${{ secrets.REGISTRY_TOKEN }} forgejo-http:3000
      - run: docker build -t http://forgejo-http:3000/whunter/hashecho:latest .
      - run: docker push http://forgejo-http:3000/whunter/hashecho:latest
